### ISSUE TITLE
Many many attempts for OTAA activation

### ISSUE THREAD

**Issue by pjb304** [pyonair/PyonAir-pycom#9]
Why does it attempt to join so many times? I've seen many attempts before it starts to send the data.  Flo has observed the same thing.  

I don't think this is due to poor LoRaWAN coverage because SNR 10.25 RSSI -69 has been observered from the node.

**Comment by FlorentinBulotAQ** [comment]
While it was doing that, I got the following errors:

`ERROR - 2020-03-24 18:16:10 - status_logger - Sending payload over LoRaWAN failed
Traceback (most recent call last):
  File "/flash/lib/LoRaWAN.py", line 120, in lora_send
Exception: LoRa is not connected`

`ERROR - 2020-03-24 18:16:36 - status_logger - Failed to read from sensor SPS030`
`ERROR - 2020-03-24 18:16:45 - status_logger - Sending payload over LoRaWAN failed
Traceback (most recent call last):
  File "/flash/lib/LoRaWAN.py", line 120, in lora_send
Exception: LoRa is not connected`

`ERROR - 2020-03-24 18:17:56 - status_logger - Sending payload over LoRaWAN failed
Traceback (most recent call last):
  File "/flash/lib/LoRaWAN.py", line 120, in lora_send
Exception: LoRa is not connected

`ERROR - 2020-03-24 18:36:46 - status_logger - Sending payload over LoRaWAN failed
Traceback (most recent call last):
  File "/flash/lib/LoRaWAN.py", line 120, in lora_send
Exception: LoRa is not connected`

`ERROR - 2020-03-24 18:42:57 - status_logger - Sending payload over LoRaWAN failed
Traceback (most recent call last):
  File "/flash/lib/LoRaWAN.py", line 120, in lora_send
Exception: LoRa is not connected`

`ERROR - 2020-03-24 18:43:39 - status_logger - Sending payload over LoRaWAN failed
Traceback (most recent call last):
  File "/flash/lib/LoRaWAN.py", line 120, in lora_send
Exception: LoRa is not connected`

**Comment by FlorentinBulotAQ** [comment]
maybe the self.lora.has_joined() method should be timed out?
